### ISSUE TITLE
pin-docker-images2 failing with src version 3.23.3

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/src-cli#432]
**Crash message**
❌ 3 errors:
   github.com/sourcegraph-testing/docker-image-pin-2:
   run: find . -name Dockerfile -type f |\
   	(... and 2 more lines)
   container: sourcegraph/dockerlint-run:latest
   standard error:
   	# ./Dockerfile:1:1: latest-image-tag
   	open ./Dockerfile: permission denied
   Command failed with exit code 123.
   Log: /tmp/changeset-github.com-sourcegraph-testing-docker-image-pin-2.234954162.log
   
**Steps to reproduce**
- Install src scli version 3.23.3
- Create a campaign with this [spec](https://demo.sourcegraph.com/users/rob/campaigns/pin-docker-image-2?tab=spec)
- Set `publish` to `false`
- Run `src campaigns preview`

**Comment by mrnugget** [comment]
I can reproduce the issue locally and ran `git bisect` to find which commit introduced it and `git bisect` tells me it's https://github.com/sourcegraph/src-cli/pull/412.

I can confirm that by running `src campaign apply` with `-workspace bind`: that works. `-workspace volume` doesn't work.

**Comment by mrnugget** [comment]
Maybe it's something with the `sourcegraph/dockerlint-run:latest` image? If I change the `steps` from this

```yaml
  - run: |
      find . -name Dockerfile -type f |\
      xargs dockerlint -w
    container: sourcegraph/dockerlint-run:latest
```

to this

```yaml
  - run: |
      find . -name Dockerfile -type f |\
      xargs cat
    container: alpine:3
```

it works, even though they both open the `Dockerfile`?
