### ISSUE TITLE
error in syncExternalService for service "OTHER" with ID 8: context deadline exceeded

### ISSUE THREAD

**Issue by cathaysia** [sourcegraph/src-cli#672]
Hi, I setup sourcegraph and src-cli by docker-compose:

```yml
version: "3.9"

services:
  sourcegraph:
    image: sourcegraph/server:3.34.2
    # container_name: sourcegraph
    # network: host
    ports:
      - 7080:7080
      - 3370:3370
    environment:
      http_proxy: ''
      https_proxy: ''
    restart: unless-stopped
    volumes:
      - sourcegraph_config:/etc/sourcegraph
      - sourcegraph_data:/var/opt/sourcegraph

  srccli:
    image: sourcegraph/src-cli
    ports:
      - 3434:3434
    volumes:
      - /home/tea/repos:/data/repos:ro
    entrypoint: ['src', 'serve-git', '/data/repos']

volumes:
   sourcegraph_config:
   sourcegraph_data: 
```

Then set src-cli in sourcegraph. For convince, I disable selinux and firewalld. But sourcegraph can not use it still:

![图片](https://user-images.githubusercontent.com/42114817/146718957-7c3b8f12-4f4c-4d0a-9243-08f09dbe1383.png)
![图片](https://user-images.githubusercontent.com/42114817/146719015-5ce2a3e4-3357-4217-be2e-3377fddcb38d.png)
![图片](https://user-images.githubusercontent.com/42114817/146719063-f4f5608c-478e-4077-84a5-22197c2bd68f.png)

I can use 10.89.0.2:3434, but the error are same :(
